# Generated by Django 5.1.7 on 2025-04-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
