# Generated by Django 5.1.7 on 2025-04-14 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_shiftgroup_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='SewingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCMPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_c', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
                ('actual', models.IntegerField(default=0)),
                ('shift1', models.IntegerField(default=0)),
                ('shift2', models.IntegerField(default=0)),
                ('shift3', models.IntegerField(default=0)),
                ('shift4', models.IntegerField(default=0)),
                ('shift5', models.IntegerField(default=0)),
                ('shift6', models.IntegerField(default=0)),
                ('shift7', models.IntegerField(default=0)),
                ('shift8', models.IntegerField(default=0)),
                ('shift9', models.IntegerField(default=0)),
                ('shift10', models.IntegerField(default=0)),
                ('shift11', models.IntegerField(default=0)),
                ('shift12', models.IntegerField(default=0)),
                ('shift13', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
                ('sewing_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sewingline')),
            ],
        ),
        migrations.CreateModel(
            name='SewingLineEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srno', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
                ('sewing_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sewingline')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shift')),
            ],
        ),
    ]
