# Generated by Django 5.1.7 on 2025-04-16 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_sewingline_employeecmpreport_sewinglineemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sewing_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.sewingline'),
            preserve_default=False,
        ),
    ]
