# Generated by Django 5.1.7 on 2025-04-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_employee_sewing_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
